In [ ]:
import numpy as np
import math
import pandas as pd
import matplotlib.pylab as py
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report
#載入資料
iris = load_iris()
x_iris = iris.data #特徵值(feature),給你變數x
y_iris = iris.target #目標值(target),給你變數x輸出y

#切分訓練資料，測試資料
x_train,x_test,y_train,y_test = train_test_split(
    x_iris,y_iris,test_size=0.3
)

#模型調試
model = LogisticRegression() #分類演算法
model.fit(x_iris,y_iris) #讓模型根據這個演算法學習

#模型預測
y_red = model.predict(x_test)

#模型評估
acc = accuracy_score(y_test,y_red)

print('reprot',classification_report(y_test,y_red,target_names=iris.target_names))



reprot               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       0.93      0.93      0.93        14
   virginica       0.95      0.95      0.95        20

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



C:\Users\dennis\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
data = {
    '姓名': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eva', 'Frank', 'Grace', 'Henry'],
    '城市': ['台北', '高雄', '台中', '台北', '高雄', '台中', '台北', '台中'],
    '教育程度': ['高中', '大學', '碩士', '博士', '大學', '高中', '碩士', '博士'],
    '收入等級': ['低', '中', '高', '高', '中', '低', '高', '中'],
    '年齡': [25, 30, 35, 40, 28, 33, 45, 38],
    '購買意願': [0, 1, 1, 1, 0, 0, 1, 1]  # 目標變數
}
df = pd.DataFrame(data)
le = LabelEncoder()
print(le.fit_transform(df['教育程度']))

[3 1 2 0 1 3 2 0]


In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
one_hold = OneHotEncoder()
categorical_data = df[['城市', '教育程度', '收入等級']]
d = np.array(df['城市'])
one_df = one_hold.fit_transform(d.reshape(-1,1)).toarray()
column_transformer = ColumnTransformer(transformers=[()])

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:


import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# 簡化的數據集
data = {
    '城市': ['台北', '高雄', '台中', '台北', '高雄'],
    '教育程度': ['高中', '大學', '碩士', '大學', '高中'],
    '年齡': [25, 30, 35, 28, 33],
    '購買': [0, 1, 1, 0, 1]
}

df = pd.DataFrame(data)
print("原始數據:")
print(df)

# 2. Label Encoding (有序類別)

print("\n🏷️ Label Encoding - 教育程度 (有序)")
print("-" * 30)

# 創建編碼器
education_encoder = LabelEncoder()

# 使用 fit_transform
df['教育程度_encoded'] = education_encoder.fit_transform(df['教育程度'])

print("\n結果:")
print(df[['教育程度', '教育程度_encoded']])

# 3. One-Hot Encoding (無序類別)

print("\n🔥 One-Hot Encoding - 城市 (無序)")
print("-" * 30)

# 創建編碼器
city_encoder = OneHotEncoder(sparse_output=False, drop='first')

# 使用 fit_transform
city_encoded = city_encoder.fit_transform(df[['城市']])

# 獲取特徵名稱
feature_names = city_encoder.get_feature_names_out(['城市'])
print(f"生成特徵: {list(feature_names)}")

# 創建 DataFrame
city_df = pd.DataFrame(city_encoded, columns=feature_names)

print("\n結果:")
result = pd.concat([df[['城市']], city_df], axis=1)
print(result)

# 4. 最終合併結果

print("\n✅ 最終編碼結果")
print("-" * 20)

# 合併所有特徵
df_final = pd.concat([
    df[['年齡']],                           # 原始數值特徵
    df[['教育程度_encoded']],               # Label encoded
    city_df,                                # One-hot encoded
    df[['購買']]                           # 目標變數
], axis=1)

print(df_final)

# 5. 新數據處理

print("\n🆕 處理新數據")
print("-" * 15)

# 新數據
new_data = pd.DataFrame({
    '城市': ['台中'],
    '教育程度': ['大學'],
    '年齡': [29]
})

print("新數據:")
print(new_data)

# 使用已訓練的編碼器 (注意：只用 transform，不用 fit_transform)
new_education = education_encoder.transform(new_data['教育程度'])
new_city = city_encoder.transform(new_data[['城市']])

print(f"\n編碼結果:")
print(f"教育程度 '大學' → {new_education[0]}")
print(f"城市 '台中' → {new_city[0]}")

# 6. 核心要點

print("\n💡 核心要點")
print("="*20)
print("Label Encoding:")
print("  • 用於有序類別 (高中 < 大學 < 碩士)")
print("  • 結果是數字 (0, 1, 2...)")

print("\nOne-Hot Encoding:")
print("  • 用於無序類別 (城市名稱)")
print("  • 結果是向量 ([1,0], [0,1]...)")

print("\nfit_transform vs transform:")
print("  • 訓練時: fit_transform()")
print("  • 新數據: transform()")

原始數據:
   城市 教育程度  年齡  購買
0  台北   高中  25   0
1  高雄   大學  30   1
2  台中   碩士  35   1
3  台北   大學  28   0
4  高雄   高中  33   1

🏷️ Label Encoding - 教育程度 (有序)
------------------------------

結果:
  教育程度  教育程度_encoded
0   高中             2
1   大學             0
2   碩士             1
3   大學             0
4   高中             2

🔥 One-Hot Encoding - 城市 (無序)
------------------------------
生成特徵: ['城市_台北', '城市_高雄']

結果:
   城市  城市_台北  城市_高雄
0  台北    1.0    0.0
1  高雄    0.0    1.0
2  台中    0.0    0.0
3  台北    1.0    0.0
4  高雄    0.0    1.0

✅ 最終編碼結果
--------------------
   年齡  教育程度_encoded  城市_台北  城市_高雄  購買
0  25             2    1.0    0.0   0
1  30             0    0.0    1.0   1
2  35             1    0.0    0.0   1
3  28             0    1.0    0.0   0
4  33             2    0.0    1.0   1

🆕 處理新數據
---------------
新數據:
   城市 教育程度  年齡
0  台中   大學  29

編碼結果:
教育程度 '大學' → 0
城市 '台中' → [0. 0.]

💡 核心要點
Label Encoding:
  • 用於有序類別 (高中 < 大學 < 碩士)
  • 結果是數字 (0, 1, 2...)

One-Hot Encoding:
  • 用於無序類別 (城市名稱)
  • 結果是向

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder,OrdinalEncoder
from sklearn.compose import ColumnTransformer
# 簡化的數據集
data = {
    '城市': ['台北', '高雄', '台中', '台北', '高雄'],
    '教育程度': ['高中', '大學', '碩士', '大學', '高中'],
    '年齡': [25, 30, 35, 28, 33],
    '購買': [0, 1, 1, 0, 1]
}
X =df.drop(columns=['購買'])
y=df['購買']
column_transformer = ColumnTransformer(transformers=[
    ('city_ohe', OneHotEncoder(), ['城市']),          # 城市用 OneHot
    ('edu_label', OrdinalEncoder(), ['教育程度']),     # 教育程度用 OrdinalEncoder（近似 LabelEncoder）
    ('passthrough', 'passthrough', ['年齡'])          # 其他欄位保持不動
])
x_tranformed = column_transformer.fit_transform(X)
x_tranformed

array([[ 0.,  1.,  0.,  2., 25.],
       [ 0.,  0.,  1.,  0., 30.],
       [ 1.,  0.,  0.,  1., 35.],
       [ 0.,  1.,  0.,  0., 28.],
       [ 0.,  0.,  1.,  2., 33.]])